"""
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C'
and 'G'.
The reverse complement of a DNA string s is the string sc formed by reversing
the symbols of s , then taking the complement of each symbol (e.g., the reverse
complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.
Return: The reverse complement sc of s.
"""

dna = "CGAAATTGACTTAAACACAAGTTTATTATAGATAGCACTGTAGTTGGCATCGCCGCAGGCCTTTTGATGCTATTAAAAGCACCGGACGCCGTTCAAAATATTGGCCGCCCATAAACCCAGTGCAAATAGATATGTTGACTAAGTGCTCCAGCGGCTTCTTCTAATAGCGAAACGAAACGCCAGTGAGAAAAACCTCTCCTAGCATATGTCAAGGAATATTACTTCCCAACTCTTATTTATGTCGCGACGAAGGAAAAAGATTCTTCTACCGCTTGCAGTAACCATTATTTTTTGTGAGGGCTAACCCCGGAATACGACGGAGAGAGTTTAGGCATGGGAGACAGGTAACGGCTATGATGCCCAGACATCCTTCTTACGGTTTTCAGCCGTAGGCATGTTCCCGCGTCCACGCTAGACCTTTGCGAGCCCACTAGAAAGATCGGTTACGAGACTAGTCTGTATGCAACATTGGTTGATTCACTGATCCTGCAAAGACCCAGGCCGTAAATTGTTAGACAGCCCATATCCGATGCTGCATTGTATGTGAAGAGAATTCAAGGGGCGTACCCCGCGACATTGTTTCGTTGGTACGACAGGCACCGTAAGTTCCAAGAACTCTTACGCTAGCGGAGCCCGCGTGGTGAGTTGGGCGTCAATGACTGACATGCAATAATGATTTGAGTGTCCGTACACTGATGCAGAGAGTTCTCGCGGACCTCGGCATTCACGTACGCCACCAAAGTCAATTACAGGAACAAATCCCGCGATTGCCTCTTGGCTATCCAATCCGTGATCGCACGGTACGGCGTCCAGCAAAGTCAACGAGGTGAAATCATGAGGACTCTTCGTAAGAATCGTGGCTTATGCAGCCCCGGCGTGTTAAGGCGGTTGCTC"
dna = dna[::-1]
reverse = dna.replace("A", "0").replace("T", "1").replace("C", "2").replace("G", "3")
reverse = reverse.replace("0", "T").replace("1", "A").replace("2", "G").replace("3", "C")

print(reverse)
