"""
Given: A DNA string of length at most 1000 nt.
Return: Four integers (separated by spaces) counting the respective number
of times that the symbols 'A', 'C', 'G', and 'T' occur in the string below
"""

nucleotides = "AGGCTCCCCGTCCACGATCCCACAGCAGGCTAGAATTGTTCCTCAGGTCGTCACAAGGAAGTGACGACACCGCCATCTGTCGCTGTATTCCGTTCCTAGCGCATTCGGCCGATCCTATGAGGAACGTCCGTAAACGATATCACCGCCTGATTAGTCGAGCATCTTTAAGAGCAGTTAAAGTCTTAAATCGCAGAATCGCAGCCTTGATATGGTCCAGAAGACGACAAAATAAACTTTATGCTTCTACTACACATCCCAGCGATTCCTCAAAGTATCTTATTGACGTTATAGAAGGTGGGAAGGAGAGTGCAGGCACAAGGACAAGGGCCCGGGTGAAAATATGGTACGAGTCCTCTGCTAATGGGGGAAATGCTTTAGCGTGTCGCAAGCATTTTTCGATGTACATTATCGTTCCACCTACCCCGTTATTTGCGTGCTACATGTGACTATCCTGACCTCAATGTAGCCGACTGTCGCCTATAAAACGATGACAGTTTGAGGATCTTTAAACAGCTGGCTACGGAGTCCCAGCTCTTCAACCCTCAGAGACGATTCAACTATGAACCATTGATTTGCCGAACAATACAGCCCCGAGTTCGATACTGACTACTAGAGTTAAGTGCCGGACGGATACGGCAGTGCTGCTCGCCTGCAGGTCGCCTCGCGATGGTTAGCGGTCGCCAACGAGTGAATATAAGACCCTGACACAGGGGACTCAGGTAGCCATGGTTCCCGATCAGACCTGATAAGTTACAGGCTCCTATTGTAAGCGACGAGGTCGCTCGCGAAAGACACGAAAGCGGCCCGCGGGCTAATGTGTTCCAGACAGCAGGTCGGCCCCAGCCTCGATG "
results = {}

for c in nucleotides:
    if c not in results:
        results[c] = 0

    results[c] += 1

resultstr = ""
for key in sorted(results.keys()):
    resultstr += str(results[key]) + str(" ")

print(resultstr)

